# Data Transformation

This Section will help you practice data transformation techniques using Pandas in Google Colab. It focuses on identifying and removing duplicates using the duplicated() and drop_duplicates() methods.

Step 1: Import Pandas and Create a DataFrame
- Import the Pandas library for data manipulation.
- Create a simple DataFrame with duplicate rows to work on.

In [ ]:
import pandas as pd

# Create a simple DataFrame with duplicate entries
frame3 = pd.DataFrame({'column 1': ['Looping'] * 3 + ['Functions'] * 4,
                       'column 2': [10, 10, 22, 23, 23, 24, 24]})

# Display the DataFrame
frame3

    column 1  column 2
0    Looping        10
1    Looping        10
2    Looping        22
3  Functions        23
4  Functions        23
5  Functions        24
6  Functions        24

 2. Identify Duplicates:
- Use the duplicated() method to identify duplicate rows.

In [ ]:
# Identify duplicate
frame3.duplicated()

0    False
1     True
2    False
3    False
4     True
5    False
6     True
dtype: bool

3. Remove Duplicates (Keep First Occurrence)
- Remove duplicate rows, keeping the first occurrence.

In [ ]:
# Remove duplicates
frame4 = frame3.drop_duplicates()

# Display the DataFrame without duplicates
frame4

    column 1  column 2
0    Looping        10
2    Looping        22
3  Functions        23
5  Functions        24

4. Remove Duplicates (Based on a Specific Column)
- Remove duplicate rows based on column 2 only.

In [ ]:
# Add a new column for demonstration
frame3['column 3'] = range(7)

# Remove duplicates based on 'column 2'
frame5 = frame3.drop_duplicates(['column 2'])

# Display the result
frame5

    column 1  column 2  column 3
0    Looping        10         0
2    Looping        22         2
3  Functions        23         3
5  Functions        24         5

5. Remove Duplicates (Keep Last Occurrence)
- Remove duplicate rows and keep the last occurrence using keep='last'.

In [ ]:
# Remove duplicates and keep the last occurrence
frame6 = frame3.drop_duplicates(['column 2'], keep='last')

# Display the result
frame6

    column 1  column 2
1    Looping        10
2    Looping        22
4  Functions        23
6  Functions        24

In [ ]:
import pandas as pd

# Sample DataFrame
data = {
    'A': [1, 2, 3, 2, 4, 5, 4],
    'B': ['x', 'y', 'z', 't', 'w', 'v', 'w']
}

df = pd.DataFrame(data)

# Remove duplicates based on column 'A', keeping the last occurrence
df_unique = df.drop_duplicates(subset=['A'], keep='last')

df_unique_1 = df.drop_duplicates(keep='last')

# Display the result
print(df_unique)

print(df_unique_1)

   A  B
0  1  x
2  3  z
3  2  t
5  5  v
6  4  w
   A  B
0  1  x
1  2  y
2  3  z
3  2  t
5  5  v
6  4  w

# Replacing Values

**Single Value Replacement**

- Create a Sample DataFrame
- Replace a Single Value:

In [ ]:
import pandas as pd
import numpy as np

replaceFrame = pd.DataFrame({
    'column 1': [200., 3000., -786., 3000., 234., 444., -786., 332., 3332.],
    'column 2': range(9)
})
print("Original DataFrame:")
print(replaceFrame)

# Replace -786 with NaN
replaceFrame.replace(to_replace=-786, value=np.nan)

Original DataFrame:
   column 1  column 2
0     200.0         0
1    3000.0         1
2    -786.0         2
3    3000.0         3
4     234.0         4
5     444.0         5
6    -786.0         6
7     332.0         7
8    3332.0         8

   column 1  column 2
0     200.0         0
1    3000.0         1
2       NaN         2
3    3000.0         3
4     234.0         4
5     444.0         5
6       NaN         6
7     332.0         7
8    3332.0         8

**Multiple Value Replacement**:

Replace Multiple Values:

In [ ]:
# Replace -786 with NaN and 0 with 2
replaceFrame.replace(to_replace=[-786, 0], value=[np.nan, 2])

   column 1  column 2
0     200.0         2
1    3000.0         1
2       NaN         2
3    3000.0         3
4     234.0         4
5     444.0         5
6       NaN         6
7     332.0         7
8    3332.0         8

**Using Dictionaries for Column-Wise Replacement**

Replace Values in Specific Columns

In [ ]:
# Replace values in 'column 1' only
replaced_dict = replaceFrame.replace({'column 1': {-786: np.nan, 3000: 1000}})

print("\nDataFrame after replacing -786 with NaN and 3000 with 1000 in 'column 1':")
print(replaced_dict)

DataFrame after replacing -786 with NaN and 3000 with 1000 in 'column 1':
   column 1  column 2
0     200.0         0
1    1000.0         1
2       NaN         2
3    1000.0         3
4     234.0         4
5     444.0         5
6       NaN         6
7     332.0         7
8    3332.0         8

**Try Replacing Strings **

In [ ]:
stringFrame = pd.DataFrame({
    'Names': ['Alice', 'Bob', 'Charlie', 'Alice', 'Eve'],
    'Scores': [85, 92, 88, 85, 90]
})

print("\nOriginal DataFrame with strings:")
print(stringFrame)

# Replace 'Alice' with 'Alicia'
replaced_strings = stringFrame.replace('Alice', 'Alicia')

print("\nDataFrame after replacing 'Alice' with 'Alicia':")
print(replaced_strings)

Original DataFrame with strings:
     Names  Scores
0    Alice      85
1      Bob      92
2  Charlie      88
3    Alice      85
4      Eve      90

DataFrame after replacing 'Alice' with 'Alicia':
     Names  Scores
0   Alicia      85
1      Bob      92
2  Charlie      88
3   Alicia      85
4      Eve      90

# Handling Missing Data

Assume we have a chain of fruit stores all over town. Currently, the dataframe is
showing sales of different fruits from different stores. None of the stores are
reporting missing values.

In [ ]:
data = np.arange(15, 30).reshape(5, 3)
dfx = pd.DataFrame(data, index=['apple', 'banana', 'kiwi', 'grapes', 'mango'],
                   columns=['store1', 'store2', 'store3'])
print(dfx)

        store1  store2  store3
apple       15      16      17
banana      18      19      20
kiwi        21      22      23
grapes      24      25      26
mango       27      28      29

Let's add some missing values to our dataframe:

In [ ]:
dfx['store4'] = np.nan
dfx.loc['watermelon'] = np.arange(15, 19)
dfx.loc['oranges'] = np.nan
dfx['store5'] = np.nan
dfx.loc['apple', 'store4'] = 20.0
print(dfx)

            store1  store2  store3  store4  store5
apple         15.0    16.0    17.0    20.0     NaN
banana        18.0    19.0    20.0     NaN     NaN
kiwi          21.0    22.0    23.0     NaN     NaN
grapes        24.0    25.0    26.0     NaN     NaN
mango         27.0    28.0    29.0     NaN     NaN
watermelon    15.0    16.0    17.0    18.0     NaN
oranges        NaN     NaN     NaN     NaN     NaN

Characteristics of Missing Data
- Entire row can contain NaN (e.g., oranges).
- Entire column can contain NaN (e.g., store5).
- Some values in both row and column can be NaN (e.g., store4, mango).

# NaN values in pandas objects

We can use the isnull() function from the pandas library to identify NaN values:

In [ ]:
dfx.isnull()

            store1  store2  store3  store4  store5
apple        False   False   False   False    True
banana       False   False   False    True    True
kiwi         False   False   False    True    True
grapes       False   False   False    True    True
mango        False   False   False    True    True
watermelon   False   False   False   False    True
oranges       True    True    True    True    True

Complement of isnull() is notnull().

In [ ]:
dfx.notnull()

            store1  store2  store3  store4  store5
apple         True    True    True    True   False
banana        True    True    True   False   False
kiwi          True    True    True   False   False
grapes        True    True    True   False   False
mango         True    True    True   False   False
watermelon    True    True    True    True   False
oranges      False   False   False   False   False

Counting NaN Values:

- We can use the sum() method to count the number of NaN values in each store.

- Count NaN values per column

In [ ]:
dfx.isnull().sum()

store1    1
store2    1
store3    1
store4    5
store5    7
dtype: int64

Total NaN values in the DataFrame:

In [ ]:
print("Total number of NaN Values")
dfx.isnull().sum().sum()

Total number of NaN Values

15

Total number of Non-Null Values:

In [ ]:
print("Number of Non-null values")
dfx.count()

Number of Non-null values

store1    6
store2    6
store3    6
store4    2
store5    0
dtype: int64

# Handling Missing Data

One of the ways to handle missing values is to simply remove them from our dataset.

In [ ]:
dfx.store4[dfx.store4.notnull()]

apple         20.0
watermelon    18.0
Name: store4, dtype: float64

Use dropna() to drop rows containing NaN values:

In [ ]:
dfx.store4.dropna()

apple         20.0
watermelon    18.0
Name: store4, dtype: float64

Apply dropna() on the entire DataFrame

In [ ]:
dfx.dropna()

Empty DataFrame
Columns: [store1, store2, store3, store4, store5]
Index: []

**Dropping by rows**

Use how='all' to drop only rows where all values are NaN.

Output:
Rows with NaN for all columns (e.g., oranges) are removed.

In [ ]:
dfx.dropna(how='all')

            store1  store2  store3  store4  store5
apple         15.0    16.0    17.0    20.0     NaN
banana        18.0    19.0    20.0     NaN     NaN
kiwi          21.0    22.0    23.0     NaN     NaN
grapes        24.0    25.0    26.0     NaN     NaN
mango         27.0    28.0    29.0     NaN     NaN
watermelon    15.0    16.0    17.0    18.0     NaN

**Dropping Columns with All NaN Values**

Specify axis=1 to drop columns where all values are NaN


Output:
Columns like store5 are removed as they contain only NaN.

In [ ]:
dfx.dropna(how='all', axis=1)

            store1  store2  store3  store4
apple         15.0    16.0    17.0    20.0
banana        18.0    19.0    20.0     NaN
kiwi          21.0    22.0    23.0     NaN
grapes        24.0    25.0    26.0     NaN
mango         27.0    28.0    29.0     NaN
watermelon    15.0    16.0    17.0    18.0
oranges        NaN     NaN     NaN     NaN

Dropping Columns Based on a Threshold
Use thresh to define the minimum non-NaN values required to keep a column:
              
              Dropping Columns Based on a Threshold
Use thresh to define the minimum non-NaN values required to keep a column:

Output: Columns with fewer than 5 non-NaN values (e.g., store4) are dropped.

In [ ]:
dfx.dropna(thresh=5, axis=1)

            store1  store2  store3
apple         15.0    16.0    17.0
banana        18.0    19.0    20.0
kiwi          21.0    22.0    23.0
grapes        24.0    25.0    26.0
mango         27.0    28.0    29.0
watermelon    15.0    16.0    17.0
oranges        NaN     NaN     NaN

# Mathematical Operations with NaN

Handling NaN in Mathematical Operations
- NumPy: Returns NaN when encountering NaN values.
- Pandas: Ignores NaN values and processes available data.

In [ ]:
ar1 = np.array([100, 200, np.nan, 300])
ser1 = pd.Series(ar1)
ar1.mean(), ser1.mean()

(nan, 200.0)

Summing Values in a Series with NaN
Compute total sales from store4:

In [ ]:
ser2 = dfx.store4
ser2.sum()

38.0

Note: NaN values are treated as 0 during summing.

Calculating the Mean:


Compute average sales from store4:

In [ ]:
ser2.mean()

19.0

Cumulative Summing with NaN



Example of cumulative sum:

In [ ]:
ser2.cumsum()

apple         20.0
banana         NaN
kiwi           NaN
grapes         NaN
mango          NaN
watermelon    38.0
oranges        NaN
Name: store4, dtype: float64

Note: Only non-NaN values affect the cumulative sum.